### ISSUE TITLE
Send heartbeat messages

### ISSUE THREAD

**Issue by juniorz** [twstrike/libotrv4#24]
This might also need the implementation of the 'IGNORE_UNREADABLE' flag.

**Comment by tuliocasagrande** [comment]
TODO:

- [x] IGNORE_UNREADABLE flag
- [x] Make heartbeat time configurable (in OTRV4_STATE_ENCRYPTED_MESSAGES)
- [x] Build heartbeat message

**Comment by natalieesk** [comment]
[deleted todo about errors]

**Comment by claucece** [comment]
@natalieesk Why is ERROR_1 part of this issue? It is part of #2 . Errors, in fact, have not been properly defined as to implement them. When the IGNORE UNREADABLE flag is NOT set, that error is used. That error has nothing to do with heartbeats.. so why is it part of this issue?

**Comment by claucece** [comment]
And also, the IGNORE_UNREADABLE flag is not set to false. It is usually set to '0x01', which is a code that flags have. If, for example, on the future, another flag is defined.. it should be set to another code, like '0x02' or similar :)

**Comment by natalieesk** [comment]
Hey, fair question. So part of this story is implementing the IGNORE_UNREADABLE flag. As there is logic around this flag relating to errors, it seemed reasonable to include that here. So you check what happens when the flag is set and check what happens when it's not. I had perceived that other story to be more about error handling, and not the reply_with_errors part. I don't think this is too much scope creep.

What do you mean by the errors not being properly defined? They're in the spec. Is there something we wanted to change about them?

We're not setting the flag to false, that's just a comment we made at the beginning in terms of how we were thinking about it. The flags are set to 0 by default so an IGNORE_UNREADABLE flag equals 1. This is already in the code.

**Comment by claucece** [comment]
> What do you mean by the errors not being properly defined? They're in the spec. Is there something we wanted to change about them?

There is a lot of other errors that we did not include. 

The error is not part of heartbeat as the flag IGNORE_UNREADABLE is not per se for heartbeat messages.

**Comment by natalieesk** [comment]
Does not integrate with Pidgin plugin. We may want to do this as a different issue.
